#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  1 18:48:37 2025

@author: decide
"""

import geopandas as gpd
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax2 = ax.twinx()

gdf=gpd.read_file("/home/decide/Documents/CloudS/Geodatics/Partages_recus/VeloClimat/Capteurs/Recuperation_traitements_donnees/Data/Outputs/Alençon - Matthieu/Alti_Matt_track.fgb")

ax.plot(gdf.index, gdf.temperature, marker = "o", color = "red")
ax2.plot(gdf.index, gdf.altitude1, marker = "o", color = "black")